### ISSUE TITLE
possible to add RSS feed for your posts?

### ISSUE THREAD

**Issue by fortunewalla** [xiaoxiae/slama.dev#59]
Is it possible to add a RSS feed for your posts? Thanks.

**Comment by xiaoxiae** [comment]
I removed it a while back since I didn't think anybody would use it. I'll add it back :).

**Comment by fortunewalla** [comment]
Thanks. For me, the advantage of RSS feed is that different website posts & titles are collected & stored offline in one place. Also I can search through it later for keywords or topics.
